/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChangePassword.java
 *
 * Created on Feb 17, 2010, 1:29:17 PM
 */

package banking;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author sethu
 */
public class ChangePassword extends javax.swing.JPanel {

    /** Creates new form ChangePassword */
    public ChangePassword() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        newPasswordText = new javax.swing.JPasswordField();
        retypePasswordText = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        passwordText = new javax.swing.JPasswordField();
        passwordMessage = new javax.swing.JLabel();
        retypeMessage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(banking.BankingApp.class).getContext().getResourceMap(ChangePassword.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        newPasswordText.setText(resourceMap.getString("newPasswordText.text")); // NOI18N
        newPasswordText.setName("newPasswordText"); // NOI18N

        retypePasswordText.setText(resourceMap.getString("retypePasswordText.text")); // NOI18N
        retypePasswordText.setName("retypePasswordText"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        saveButton.setText(resourceMap.getString("saveButton.text")); // NOI18N
        saveButton.setName("saveButton"); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        passwordText.setText(resourceMap.getString("passwordText.text")); // NOI18N
        passwordText.setName("passwordText"); // NOI18N
        passwordText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTextFocusLost(evt);
            }
        });

        passwordMessage.setForeground(resourceMap.getColor("passwordMessage.foreground")); // NOI18N
        passwordMessage.setText(resourceMap.getString("passwordMessage.text")); // NOI18N
        passwordMessage.setName("passwordMessage"); // NOI18N

        retypeMessage.setForeground(resourceMap.getColor("retypeMessage.foreground")); // NOI18N
        retypeMessage.setText(resourceMap.getString("retypeMessage.text")); // NOI18N
        retypeMessage.setName("retypeMessage"); // NOI18N

        jLabel4.setForeground(resourceMap.getColor("jLabel4.foreground")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setForeground(resourceMap.getColor("jLabel5.foreground")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(saveButton)
                            .addComponent(newPasswordText)
                            .addComponent(passwordText)
                            .addComponent(retypePasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordMessage)
                            .addComponent(retypeMessage)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordMessage)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retypePasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(retypeMessage)
                    .addComponent(jLabel5))
                .addGap(40, 40, 40)
                .addComponent(saveButton)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void passwordTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextFocusLost
        // TODO add your handling code here:
        String p=passwordText.getText().trim();
        String u = "admin";
        String sql = "select * from users where username='" + u + "' and password='" + p + "' ";
        DBConnect dbcon = new DBConnect();
        ResultSet rs = null;
        try {
            rs = dbcon.stmt.executeQuery(sql);
            if (!rs.next()) {
                jLabel4.setText("Wrong Password");
                saveButton.setEnabled(false);
                return;
            }
            else{
                jLabel4.setText("");
                saveButton.setEnabled(true);
            }
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_passwordTextFocusLost

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if(!newPasswordText.getText().equals(retypePasswordText.getText())){
            jLabel5.setText("Passwords Do Not Match");
            return;
        }
        else{
            jLabel5.setText("");
        }
        new Model().changePassword("admin",newPasswordText.getText().trim());
        JOptionPane.showMessageDialog(this,"Password Changed Successfully","Done",JOptionPane.PLAIN_MESSAGE);
        passwordText.setText("");
        newPasswordText.setText("");
        retypePasswordText.setText("");
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField newPasswordText;
    private javax.swing.JLabel passwordMessage;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JLabel retypeMessage;
    private javax.swing.JPasswordField retypePasswordText;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

}
