/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Transact.java
 *
 * Created on Feb 16, 2010, 7:48:01 PM
 */

package banking;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author sethu
 */
public class Transact extends javax.swing.JPanel {

    /** Creates new form Transact */
    JTextField jtf = null;
    public Transact() {
        initComponents();
        setModel("");
        jtf = (JTextField) usernameCombo.getEditor().getEditorComponent();
        jtf.addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent e) {
                usernameComboKeyReleased(e);
            }
            
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        creditRadio = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        usernameMessage = new javax.swing.JLabel();
        amountMessage = new javax.swing.JLabel();
        usernameCombo = new javax.swing.JComboBox();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(banking.BankingApp.class).getContext().getResourceMap(Transact.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        creditRadio.setSelected(true);
        creditRadio.setText(resourceMap.getString("creditRadio.text")); // NOI18N
        creditRadio.setName("creditRadio"); // NOI18N
        creditRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditRadioActionPerformed(evt);
            }
        });

        jRadioButton2.setText(resourceMap.getString("jRadioButton2.text")); // NOI18N
        jRadioButton2.setName("jRadioButton2"); // NOI18N
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        amountText.setText(resourceMap.getString("amountText.text")); // NOI18N
        amountText.setName("amountText"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        usernameMessage.setForeground(resourceMap.getColor("usernameMessage.foreground")); // NOI18N
        usernameMessage.setText(resourceMap.getString("usernameMessage.text")); // NOI18N
        usernameMessage.setName("usernameMessage"); // NOI18N

        amountMessage.setForeground(resourceMap.getColor("amountMessage.foreground")); // NOI18N
        amountMessage.setText(resourceMap.getString("amountMessage.text")); // NOI18N
        amountMessage.setName("amountMessage"); // NOI18N

        usernameCombo.setEditable(true);
        usernameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1" }));
        usernameCombo.setName("usernameCombo"); // NOI18N
        usernameCombo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                usernameComboCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        usernameCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameComboKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameComboKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amountMessage)
                    .addComponent(jButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(creditRadio)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(usernameMessage))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(usernameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameMessage)
                    .addComponent(usernameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(creditRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amountMessage)
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void creditRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditRadioActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
    }//GEN-LAST:event_creditRadioActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        creditRadio.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    void setModel(String username){
        try {
            ResultSet rs = new Model().getUsernamesStartsWith(username);
            Vector v = new Vector();
            while (rs.next()) {
                v.add(rs.getString("username"));
            }
            DefaultComboBoxModel dcm = new DefaultComboBoxModel(v);
            usernameCombo.setModel(dcm);
        } catch (SQLException ex) {
            Logger.getLogger(Transact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jtf.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter a valid username","Error",JOptionPane.ERROR_MESSAGE);
            usernameMessage.setText("Please provide student username");
            usernameCombo.requestFocus();
            return;
        }
        if(!(new Model()).validateUsername(jtf.getText().trim())){
            JOptionPane.showMessageDialog(this,"Student Not Found","Error",JOptionPane.ERROR_MESSAGE);
            //usernameText.selectAll();
            usernameMessage.setText("Student was not found");
            return;
        }
        else{
            int amount=0;
            try{
                amount = Integer.parseInt(amountText.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this,"Please Enter a Valid Amount","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(creditRadio.isSelected()){
                amount*=-1;
            }
            new Model().transaction(jtf.getText().trim(), amount);
            JOptionPane.showMessageDialog(this,"Transaction has been processed","Done",JOptionPane.PLAIN_MESSAGE);
            //usernameText.setText("");
            amountText.setText("0");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usernameComboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameComboKeyReleased
        // TODO add your handling code here:
       //System.out.println("key released");
        int code = evt.getKeyCode();
        if(code == KeyEvent.VK_ENTER){
           usernameCombo.setPopupVisible(false); 
           return;
        }
        if(code == KeyEvent.VK_ESCAPE){
           usernameCombo.setPopupVisible(false); 
           return;
        }
        if(code == KeyEvent.VK_DOWN){
            return;
        }
        if(code == KeyEvent.VK_UP){
            return;
        }
        setModel(jtf.getText().trim());
        usernameCombo.setPopupVisible(true);
}//GEN-LAST:event_usernameComboKeyReleased

    private void usernameComboKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameComboKeyTyped
        // TODO add your handling code here:
        //usernameComboKeyReleased(evt);
    }//GEN-LAST:event_usernameComboKeyTyped

    private void usernameComboCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_usernameComboCaretPositionChanged
        // TODO add your handling code here:
   //     
     //  usernameCombo.showPopup();
    }//GEN-LAST:event_usernameComboCaretPositionChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountMessage;
    private javax.swing.JTextField amountText;
    private javax.swing.JRadioButton creditRadio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JComboBox usernameCombo;
    private javax.swing.JLabel usernameMessage;
    // End of variables declaration//GEN-END:variables

}
